version: '3.8'

services:
  bookcow-api:
    build: .
    networks:
      - backend
    depends_on:
      bookcow-db:
        condition: service_healthy
      bookcow-keycloak:
        condition: service_healthy

    ports:
      - '8080:8080'
    environment:
      - DB_HOST=bookcow-db
      - DB_PORT=5432
      - DB_NAME=bookcow-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  bookcow-db:
    image: postgres:13.8
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookcow-db
    ports:
      - '9432:5432'
    healthcheck:
      test: pg_isready -U postgres -d bookcow-db
      interval: 10s
      timeout: 3s
      retries: 3

  bookcow-keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7080/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - local_network

networks:
  backend:
  local_network:
    driver: bridge
