version: '3.8'

services:
  bookcow-api:
    build: .
    networks:
      - backend
    depends_on:
      bookcow-db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=bookcow-db
      - DB_PORT=5432
      - DB_NAME=bookcow-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  bookcow-db:
    image: postgres:13.8
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookcow-db
    ports:
      - '9432:5432'
    healthcheck:
      test: pg_isready -U postgres -d bookcow-db
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  backend:

