application:
  name: Work4Free API

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update #create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.uri}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  uri: http://localhost:7080
  realm: dev

springdoc:
  api-docs:
    enabled: true

logging:
  level:
    root: INFO